### ISSUE TITLE
Edge now supports CSP 2.0

### ISSUE THREAD

**Issue by renchap** [twitter/secure_headers#358]
MS Edge is now supporting CSP 2.0: https://blogs.windows.com/msedgedev/2017/01/10/edge-csp-2/

Edge build 15002 (https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/15002/) has been released in january.

This is breaking our application when loading Webworkers from `blob:` as `secureheaders` is not sending `child-src` (but `frame-src`), so Edge defaults to `default-src`.

I tried to change `EDGE_DIRECTIVES = DIRECTIVES_1_0` to `EDGE_DIRECTIVES = DIRECTIVES_2_0` and it solved the problem, but I guess a proper fix requires checking the Edge build number. I can do it if you confirm this is the correct fix.

**Comment by oreoshake** [comment]
So edge ignores `frame-src` ⁉️ if so, that's terrible. IIRC the w3c is undeprecating `frame-src` anyways.

Do older versions support `child-src`? Can we send that unconditionally? Can we send both without generating console warnings?

This child/frame src thing has been a serious pain.

**Comment by renchap** [comment]
Here is a CSP report I got using the latest Edge, triggered when loading a WebWorker using a `blob:` URL:

```
{
    "csp-report": {
        "document-uri": "https://www.talegraph.com/tales/xxx",
        "blocked-uri": "blob",
        "violated-directive": "default-src 'self'",
        "original-policy": "default-src 'self'; connect-src 'self' wss://www.talegraph.com sentry.io api.segment.io api.mixpanel.com wss://*.crisp.chat storage.googleapis.com; font-src 'self' data: fonts.gstatic.com client.crisp.chat; frame-src 'self' blob:; img-src 'self' www.google-analytics.com client.crisp.chat image.crisp.chat data: blob: pi.prod.talegraph.net; media-src 'self' client.crisp.chat; object-src 'none'; script-src 'self' www.google-analytics.com cdn.segment.com cdn.mxpnl.com client.crisp.chat; style-src 'self' 'unsafe-inline' fonts.googleapis.com client.crisp.chat; report-uri https://talegraph.report-uri.io/r/default/csp/enforce",
        "effective-directive": "worker-uri",
        "status-code": 200
    }
}
```

It looks like it does not use `frame-src`. I do not know how to install old Edge versions to check when the behaviour changed, but I guess it would have changed when they implemented CSP 2.0.

**Comment by oreoshake** [comment]
> `"effective-directive": "worker-uri",`

`worker-uri`?

**Comment by renchap** [comment]
Dont ask me 🤷‍♂️

**Comment by oreoshake** [comment]
Well, I'm assuming implementing `worker-src` will make everything work. I have to think `frame-src` still works, it just doesn't cover webworkers but I haven't tested any of this out.

**Comment by renchap** [comment]
`worker-src` is in CSP 3, but Edge seems to only be implementing CSP 2.
I spent quite some time trying to understand what is happening but I am not sure I got everything.

Would it be a start to change the gem to send CSP 2 headers to recent Edge?

**Comment by oreoshake** [comment]
> Would it be a start to change the gem to send CSP 2 headers to recent Edge?

Sure, but I'd love to know if we can send the same header to all versions of edge.

**Comment by renchap** [comment]
I did not find how to rollback Edge, or an Edge 14 vm on modern.ie.
It looks like BrowserStack supports Edge 14, I never used it but I will see if I manage to get it working.

**Comment by renchap** [comment]
I managed to test it with Edge 14 on BrowserStack. WebWorker from blob works fine with this CSP header:
`Content-Security-Policy: default-src 'self'; child-src blob: ; script-src 'self' 'unsafe-inline';`

I have not been able to find out how to test with even earlier versions.

A basic test for loading Webworkers from blobs:
```html
<html>
  <body>
    <script>
      var code = "self.onmessage=function(e){postMessage('Worker: '+e.data);}";
      var blob = new Blob([code], {type: 'application/javascript'});
      var worker = new Worker(URL.createObjectURL(blob));

      worker.onmessage = function(e) {
        alert('Response: ' + e.data);
      };
      worker.postMessage('Test');
    </script>
  </body>
</html>
```

**Comment by nstarr** [comment]
Hey everyone, I'm a Program Manager on the Edge team. I reached out to one of the engineers who works on CSP and this what he says is the behavior in the Windows 10 Creators Update:

"Frame-src never applies to worker.

It used to be script-src of that applies to initial worker script. CSP 2 uses child-src while CSP 3 uses worker-src. Edge currently try to check against worker-src, if that is not there, try child-src, and then default-src.

For frame, CSP 1 uses frame-src, CSP 2 uses child-src and CSP 3 back to frame-src. Edge tries frame-src first, then child-src and then default-src."

Hopefully this helps clear things up. Let me know if you have any other questions!

**Comment by oreoshake** [comment]
Thanks, that all makes sense. 

The only remaining question is what's up with that effective-directive value of worker-uri?

**Comment by nstarr** [comment]
Ah! Good catch, that's actually a bug. It should be "worker-src" as per the spec. I'll get this filed internally and addressed. If you want, you can also file the issue in our public tracker: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/. 

Thanks for the find!

**Comment by oreoshake** [comment]
I'll happily file an issue, I had no idea there was a public bug tracker!

**Comment by oreoshake** [comment]
Fixed in https://github.com/twitter/secure_headers/pull/390 when we removed all UA sniffing
