### ISSUE TITLE
Consider removal of support for HPKP?

### ISSUE THREAD

**Issue by stve** [twitter/secure_headers#368]
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ

**Comment by oreoshake** [comment]
Yep. Let's deprecate now and remove when they do.

**Comment by oreoshake** [comment]
Cc @ejcx

**Comment by EvanHahn** [comment]
This header is [supported by browsers other than Chrome](https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning#Browser_compatibility). Should this be removed if Firefox doesn't intend to remove it?

**Comment by oreoshake** [comment]
@EvanHahn I wasn't aware firefox doesn't intend to remove it. 

That would change my feeling a little but I think the consensus is that CT logs provide enough value for everyone while hpkp benefits a small group while endangering everyone else.

**Comment by EvanHahn** [comment]
Sorry, I think I've misled—I don't know whether Firefox intends to remove it or not because I didn't do any sleuthing. I can try to hunt around to see if they have anything about it on their radar, if helpful.

**Comment by oreoshake** [comment]
@EvanHahn Please do let us know. It's my understanding that there's no general disagreement with this direction (even if hpkp was great for GitHub).

**Comment by EvanHahn** [comment]
I found [this Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1412438). Based on that alone (couldn't see anything else in their bug tracker), it seems like it's being considered but it's not definitive yet.

**Comment by oreoshake** [comment]
I'm reopening this one. I committed a fix but will need to deprecate before removing.
