### ISSUE TITLE
Discussion: integration with Rails 5.2 CSP feature

### ISSUE THREAD

**Issue by renchap** [twitter/secure_headers#375]
There have been several tentatives to merge this gem into Rails. CSP support has been merged and will be released in Rails 5.2: https://github.com/rails/rails/pull/31162

I gave a quick look at it and it does not replace this gem, but it seems a good idea to get the two work together, and maybe use the Raisl API. Any thoughts?

**Comment by jacobbednarz** [comment]
I haven't delved too deeply into what is on offer with the current Rails
DSL in 5.x other than the basic directives however that will be no good
for my monorail or GitHub considering both are running Rails < 5 (and I
can't imagine we are the only ones on older versions at this stage).
We're working on the 5.x migration however we have quite a bit of
custom code that needs to be ported. I'm also not really inclined to
backport this CSP patch to 3.x/4.x for the purpose of moving it into
this gem considering this is working as is.

However on the flip side to this, I remember @oreoshake [not being
entirely happy](https://github.com/twitter/secureheaders/issues/280#issuecomment-237702300) with some of the inner workings of the CSP functionality
which this might be a prime time to look at deprecating in favour of the
Rails API. Forking the execution path into something like this:

```ruby   
if Rails.config.csp?
  # load up the secure_headers file for setting the inbuilt Rails API
  # and adjusting accordingly with a plan to deprecate this block
  # eventually...
else
  # require all the existing CSP files
end
```

One concern I have is that Rails hasn't really ever showed interest in
being on the front foot with things like CSP and that leaves those who
want to help by being early adopters of changes forced to carry around
monkey patches or custom forks when upstream proposals are made. Who
knows, perhaps this will get better once it's _in_ Rails core :man_shrugging:

In it's current state, there is a fair bit of functionality lacking
(different UA behaviours, ability to have an enforced + report only
policy) which leads me to wanting to wait until the API matures a bit
more before throwing effort at supporting it. Depending on how quickly
we can get to Rails 5, this might be something I can fix.

**Comment by renchap** [comment]
My main reason for opening the discussion is that I remember https://github.com/rails/rails/issues/27583
This gem has definitely more features and will always be needed to people on Rails 5.2, but I feel it is worth it to discuss further/better integration with the future Rails versions.

**Comment by oreoshake** [comment]
`secure_headers` technically has little to do with rails at all, it's for `rack` applications.

I think the effort in rails/rails is great and something I want to encourage people to use. Yes, it lacks some features but in the long run it will be the better tool. The features it does lack are mostly insignificant (caching policies, dedup logic, browser console warning mitigation*). As for per-request customization, `secure_headers` has *different* but not necessarily better support.

`secure_headers` was always (mostly) driven by what my current employer's apps demand and therefor will never be better than what rails/rails does in the end. I'm surprised as many of y'all came along for this ride.

In an ideal world, this gem is obsoleted by rails and it goes on as a `rack` library. But as @jacobbednarz mentions, things will certainly be supported for some time (or at least until we upgrade to 5.2 :trollface:).

\* browser console warnings and *significant* differences (`frame` vs `child` src values) between browsers are almost non-existent at this point

**Comment by oreoshake** [comment]
IOW I don't see the two intermixing, I see them diverging. I love being wrong so I'm not saying I wouldn't consider it!

**Comment by oliverguenther** [comment]
> The features it does lack are mostly insignificant.

An important thing that drove us to using `secure_headers` are the nonce and hash based script tags which is crucial if you have a large archaic Rails monolith that uses lots of inline tags. There is an open issue to implement that at https://github.com/rails/rails/issues/31689 but I wonder whether its a good idea to reinvent these features instead of seeking to collaborate.

**Comment by oreoshake** [comment]
Agree, nonces (ha) are necessary. I think porting this behavior into their framework would not be hard. I could see myself contributing a patch.

The hash implementation however, is garbage and should not be ported 😆.

**Comment by oreoshake** [comment]
Now that nonces are a part of vanilla rails, I think that's one more argument towards archiving this project. Until GitHub fully replaces secure_headers with the built-in features, I will keep this open. Once GitHub moves to the built-in support, I plan on archiving this project. As a policy I don't support libraries I don't use.

**Comment by oreoshake** [comment]
I wanted to archive this project but I've been putting a fair amount of support into the project. That being said, I think the idea of integrating the two APIs probably isn't worth the hassle and there isn't much to be gained.
