### ISSUE TITLE
Remove all UA sniffing?

### ISSUE THREAD

**Issue by oreoshake** [twitter/secure_headers#384]
UA sniffing is a tricky beast. While it can help optimize security, it's very error prone. See https://github.com/twitter/secureheaders/issues/381 for a recent example. CSP, when implemented correctly, is backwards compatible and somewhat safe on modern browsers.

It sounds like safari is set on keeping a static UA (locking all future versions to 11.2): https://twitter.com/rmondello/status/956236581987172354 I don't think Safari is making the right move here and while I could be entirely wrong, we cannot rely on it for feature detection going forward for modern browsers. **This could be an issue for people who have to support older browsers**.

I don't think this will break anything (on modern browsers). Safari 10 has good CSP 2 support. Chrome (and Opera) and Firefox support is similar enough. Edge/IE don't break in any unexpected way.

### :fire: UA sniffing? :fire: 

It's only there to cover up behavior from browsers from 3+ years or so ago in some cases. 

**If this introduces a few console messages, would everyone come at me with pitchforks**?

**Comment by oreoshake** [comment]
For the record, this would be the second time UA sniffing would be ripped out entirely.

**Comment by jacobbednarz** [comment]
I don't care for console warnings but the reporting endpoint spam might be troublesome (especially for folks for report-uri.io).

> For the record, this would be the second time UA sniffing would be ripped out entirely.

Third time's a charm, right?

**Comment by oreoshake** [comment]
We could automatically throttle reporting for safari oh wait that would require UA sniffing

**Comment by paulfri** [comment]
Similar to #381, I discovered today from a bug report that `script-src 'strict-dynamic'` is broken in Vivaldi because secure_headers isn't sending the nonce in the CSP header. I considered filing a separate bug, but if you're getting rid of UA sniffing, then the backwards-compatible approach would be a reasonable fix as well.

**Comment by oreoshake** [comment]
@paulfri have you upgrade to 6.0.0.alpha01? That should be fixed in the latest alpha

**Comment by paulfri** [comment]
Yep, fixed in the alpha, I'll just upgrade ASAP. Thanks.

**Comment by oreoshake** [comment]
I've created a PR for this: https://github.com/twitter/secureheaders/pull/390
