### ISSUE TITLE
Add support for prefetch-src directive

### ISSUE THREAD

**Issue by toao** [twitter/secure_headers#388]
Currently the ```prefetch-src``` directive is not included in this gem, it should be added because e.g. the latest chrome (65) supports it.

All details can be found at https://w3c.github.io/webappsec-csp/#directive-prefetch-src

```
The prefetch-src directive restricts the URLs from which resources may be
prefetched or prerendered. The syntax for the directive’s name and value is
described by the following ABNF:

directive-name  = "prefetch-src"
directive-value = serialized-source-list

Given a page with the following Content Security Policy:

Content-Security-Policy: prefetch-src https://example.com/

Fetches for the following code will return network errors, as the URLs
provided do not match prefetch-src's source list:

<link rel="prefetch" src="https://example.org/"></link>
<link rel="prerender" src="https://example.org/"></link>
```

**Comment by oreoshake** [comment]
Interesting, I hadn't heard of this one coming up. This seems like it would break things since it inherits from `default-src`. I've been preaching that `'none'` is the only valid value for `default-src`.
