### ISSUE TITLE
Missing VERSION constant

### ISSUE THREAD

**Issue by jondeandres** [twitter/secure_headers#397]
In secure_headers 2.x the library had a `SecureHeaders::VERSION` constant. The interface in the library has changed several times and trying to integrate a library with the different versions is a drama without that constant.

Can I ask the reason you preferred not having a so useful constant? Relying on rubygems to take the gem version is not ideal.

**Comment by oreoshake** [comment]
I can't remember *why* it changed but does `Gem::Specification.find_by_name("secure_headers").version` more or less get you the same information?

**Comment by jondeandres** [comment]
Yes, but that means requiring rubygems in the library and that is a bad
practice afaik.

**Comment by oreoshake** [comment]
We now have a version constant
