### ISSUE TITLE
6.1 is a breaking change due to removed HPKP

### ISSUE THREAD

**Issue by ivanreese** [twitter/secure_headers#399]
I just upgraded to 6.1, which removed support for HPKP (in commit b208b8a). This change wasn't captured in the changelog, and it broke my build.

I'm not sure whether you'd want to just amend the changlog to reflect this, or pull 6.1 and cut a 7.0.

**Comment by oreoshake** [comment]
Sorry, this is :100: my fault. I had forgot about the breaking change, saw a different change, realized it wasn't an issue, and pushed forward. 

HPKP is dead, please remove the config.

**Comment by ivanreese** [comment]
Already did, no sweat. Feel free to close this issue — but it might be nice to add a note to the changelog while you're at it.

**Comment by oreoshake** [comment]
I added https://github.com/twitter/secure_headers/commit/543e6712aadae08f1653ed973e6b6204f7eac26a but I think there's value in leaving this issue open.
