### ISSUE TITLE
Allow for overriding cookie policy on a request by request basis

### ISSUE THREAD

**Issue by mikefrederick** [twitter/secure_headers#401]
I am currently using the default cookie policy:

```
SecureHeaders::Configuration.default do |config|
    config.cookies = {
      secure: true,
      httponly: true,
      samesite: {
        lax: true
      }
    }
end
```

However, I would like to allow my session cookie to be used within an iframe on certain requests. This would require the removal of the SAMESITE attribute of the cookie, as neither `lax` nor `strict` would allow the cookie to be used in this situation.

As far as I can tell, there is no way to change this cookie policy on a single request, but there is validity to doing so.

Is this something that the team feels would warrant a pull request? Is there some way to do this that I am missing?

**Comment by oreoshake** [comment]
@mikefrederick can you double check my understanding of the situation?

You have a session cookie and you have some iframed content. The `samesite=lax` cookie is not being sent to the iframe. You'd like it to be sent to the iframe. 

Is your site framing your content or is this a 3rd party framing your content? I haven't dug through the samesite behavior but I'm slightly surprised at this behavior if it's a "samesite" frame load. Would a use be in both contexts at once or are these things walled off such that a user wouldn't typically only experience one scenario at a time.

> As far as I can tell, there is no way to change this cookie policy on a single request, but there is validity to doing so.

I think you'd get mixed up fairly quickly if you're changing attributes of the same cookie. I'm not here to ask you to redesign things :smile: 

If my assumption about both your use case and the samesite behavior is correct, I think I have a workaround:

Set two cookies with the same value, one `samesite=lax` and the other without the attribute. For the framed requests, you could use the non-samesite cookie. For standard requests, you could read the same site cookie. You could compare the two cookies and ensure their values match for extra safety. Assuming all of your frame loads don't change application state, I think this could work out.

We use this approach, sending two cookies with different samesite values, and I think it would support your use case without a library change. WDYT?

**Comment by oreoshake** [comment]
We recently implemented this using the standard override feature.

**Comment by oreoshake** [comment]
@mikefrederick to expand on my comment yesterday, we dynamically apply cookie logic - we're rolling it out to staff first. 

```ruby
SecureHeaders::Configuration.override(:preview_policy_samesite_lax) do |config|
  config.cookies = {
    samesite: {
      lax: true
    }
  }
end

def some_before_action 
  if staff?
    SecureHeaders.use_secure_headers_override(request, :preview_policy_samesite_lax)
  end
end
```

**Comment by oreoshake** [comment]
Please feel free to reopen if this didn't solve your use case.
