### ISSUE TITLE
Differentiate CSP headers by browser

### ISSUE THREAD

**Issue by slayer** [twitter/secure_headers#402]
Hi there

Problem:  CSP support in browsers is far from perfect
eg: Safari complaints to `report-sample`
![image](https://user-images.githubusercontent.com/57521/60048337-99424100-96d4-11e9-999c-6577e0faca5a.png)

Is there easy way to send only compatible CSP headers based on UserAgent header ? 

Thanks

**Comment by oreoshake** [comment]
Hi @slayer, for most of its life, `secure_headers` did user agent sniffing with the goal of minimizing console noise. There are probably tons of leftover code artifacts around supporting that. It ended up breaking random things many different times, preventing people from making legit changes, etc. It's a losing battle IMO.

**Comment by slayer** [comment]
I see. Thank you for response

What do you think about simple hook so end developer can be able customize headers ? 

like:
```ruby
  csp.csp_hook = -> (csp, env) {
    if csp != SecureHeaders::OPT_OUT && env['HTTP_USER_AGENT'] =~ /Safari/
      csp[:script_src].delete_at(csp[:script_src].index('report-sample'))
    end    
  }
```

**Comment by oreoshake** [comment]
You can accomplish that today with a filter and an override, although it would be nice to have it all in one place like you propose.

In `ApplicationController`

```ruby
before_action :filter_csp

def filter_csp
  if request.user_agent =~ /Safari/ # Side note, you'd want to actually parse it because this matches chrome and Edgium
    override_value = SecureHeaders.config_for(request)[:script_src].delete_at(csp[:script_src].index('report-sample'))
    override_content_security_policy_directives(script_src: override_value)
  end
end
```

(Note, I haven't actually tested this out so it may not be syntactically correct but I'm fairly certain I'm not making things up :smile:)

I'm not sure if you're aware, but this library is more or less in maintenance mode. I would recommend using the built-in rails CSP API if possible and focusing on improving the standard implementation. If you're not using rails, this project will be archived at some point.

**Comment by slayer** [comment]
Oh
Thank you for the example of code, I forget about `override_content_security_policy_directives`

I started using secure_headers long time ago and did not aware that in Rails appeared its own CSP API
I will close this issue. Thank you for info
