### ISSUE TITLE
Enable HSTS conditionally depending on domain

### ISSUE THREAD

**Issue by vitobotta** [twitter/secure_headers#408]
Hi, I am looking to add this gem to my Rails app. The app allows users to add custom domains, and for these domains I need to be able to use both HTTP and HTTPS because of LetsEncrypt's HTT01 verification. However for the app itself, when using its own domain, I want to enable HSTS. How do I enable it conditionally for that domain only? Thanks!

**Comment by oreoshake** [comment]
That use case isn't really supported by this library. I think you'd need some logic in your code to decide whether or not the header is set.

**Comment by vitobotta** [comment]
I see. Thanks for replying :)
