### ISSUE TITLE
How to set SameSite to 'None' instead of Lax or Strict in 3.x?

### ISSUE THREAD

**Issue by suresh4154** [twitter/secure_headers#412]

**Comment by oreoshake** [comment]
Hi @suresh4154, that currently isn't supported.

To add support, we'd have to allow it in validation code e.g.

https://github.com/twitter/secure_headers/blob/1fa2083cf9b1749aaa5a2608636ca06085ec9cb2/lib/secure_headers/utils/cookies_config.rb#L45-L51

And have it understand the new value 

https://github.com/twitter/secure_headers/blob/1fa2083cf9b1749aaa5a2608636ca06085ec9cb2/lib/secure_headers/headers/cookie.rb#L92-L98

I think that's all that would be required.

**Comment by suresh4154** [comment]
Thanks @oreoshake .

**Comment by oreoshake** [comment]
I think this is worth implementing fwiw

**Comment by ilikepi** [comment]
@oreoshake Is there any chance this could be backported to the 3.x branch?  I'd be happy to kick out a PR if it would help.

**Comment by oreoshake** [comment]
I'm going to re-open this issue. I suspect this samesite change is going to be more painful than anticipated.

@ilikepi I'd be happy to merge and release if you get things working! I didn't realize we had cookie support in 3.x but then again, 4/5/6 came out in quick succession. How does time work?

**Comment by ilikepi** [comment]
Submitted #416 by cherry-picking commits from #414, with some minor tweaks.

**Comment by oreoshake** [comment]
This has been released in 3.7.4

That leaves the 4/5.x lines. I'm happy to backport and release for anyone else who needs a specific line to support this.
