### ISSUE TITLE
Safari does not support worker-src

### ISSUE THREAD

**Issue by figandbones** [twitter/secure_headers#413]
Is there a way to not send the worker-src part of the directive when the browser is Safari?
It would be nice to avoid the error: Unrecognized Content-Security-Policy directive 'worker-src'.

**Comment by oreoshake** [comment]
No user agent sniffing is done in this library (anymore). You could probably accomplish that with something like this 

```ruby
If safari?
  override_content_security_policy_directives(worker_src: nil)
end
```

**Comment by figandbones** [comment]
Thanks for your response, oreoshake. Unfortunately that didn't work. I noticed that config.csp has @ variables, so the line:
``config.csp.merge!(additions)``
didn't have any effect.

**Comment by oreoshake** [comment]
Sorry @figandbones, it should be `SecureHeaders::OPT_OUT` instead of `nil`.

**Comment by figandbones** [comment]
Thanks! That works.
