### ISSUE TITLE
README.md states Apache license, LICENSE file contains MIT license

### ISSUE THREAD

**Issue by lgarron** [twitter/secure_headers#415]
https://github.com/twitter/secure_headers/blob/master/README.md#license says:

> Licensed under the Apache License, Version 2.0: http://www.apache.org/licenses/LICENSE-2.0

`LICENSE` contains the text of the MIT license.

GitHub picks up the MIT license, but I ran into an issue with license detection because of the `README.md` license. Presumably the exact licensing situation should be fully spelled out and consistent?

**Comment by oreoshake** [comment]
The move to MIT was [previously approved](https://github.com/twitter/secure_headers/pull/315) so it's a case of the README being inaccurate.
